### ISSUE TITLE
请问怎么用呢

### ISSUE THREAD

**Issue by yesee** [DawnFz/SG.Plugin.Injury.Calculator#1]
下载了文件放到Plugins文件夹下不可行

**Comment by DawnFz** [comment]
不要修改文件名，请使用原文件名




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月2日(星期三) 晚上9:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [DawnFz/SG.Plugin.Injury.Calculator] 请问怎么用呢 (Issue #1)





 
下载了文件放到Plugins文件夹下不可行
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Lightczx** [comment]
下载右侧的release
